import type {
  DemoChatSession,
  DemoFoodLog,
  DemoGoal,
  DemoRecipe,
  NutritionAssistantDemoState,
} from './types';

const goals: DemoGoal[] = [
  { nutrient: 'calories', target_value: 1600, unit: 'kcal', goal_type: 'goal' },
  { nutrient: 'protein_g', target_value: 132, unit: 'g', goal_type: 'goal' },
  { nutrient: 'carbs_g', target_value: 150, unit: 'g', goal_type: 'goal' },
  { nutrient: 'fat_total_g', target_value: 53, unit: 'g', goal_type: 'goal' },
  { nutrient: 'fiber_g', target_value: 25, unit: 'g', goal_type: 'goal' },
  { nutrient: 'sugar_g', target_value: 40, unit: 'g', goal_type: 'limit' },
  { nutrient: 'sodium_mg', target_value: 1500, unit: 'mg', goal_type: 'limit' },
  { nutrient: 'hydration_ml', target_value: 2987, unit: 'ml', goal_type: 'goal' },
];

const logs: DemoFoodLog[] = [
  {
    id: 'log-bagel',
    log_time: '2026-04-20T08:30:00.000Z',
    food_name: 'Half cinnamon raisin bagel',
    calories: 165,
    protein_g: 4.1,
    carbs_g: 31,
    fat_total_g: 1.5,
    fiber_g: 1.8,
    sugar_g: 8,
    sodium_mg: 145,
    hydration_ml: 0,
    serving_size: 'half large NYC bagel',
    portion: '1/2 bagel',
    confidence: 'medium',
    error_sources: ['vague_portion', 'no_data'],
  },
  {
    id: 'log-water-morning',
    log_time: '2026-04-20T09:10:00.000Z',
    food_name: 'Water',
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    hydration_ml: 964,
    serving_size: '32 oz',
    portion: '32 oz',
    confidence: 'high',
  },
  {
    id: 'log-garlic-knot',
    log_time: '2026-04-20T12:25:00.000Z',
    food_name: 'Garlic knot with marinara',
    calories: 225,
    protein_g: 6.4,
    carbs_g: 28,
    fat_total_g: 9.4,
    fat_saturated_g: 1.4,
    fiber_g: 2.1,
    sugar_g: 4,
    sodium_mg: 349,
    hydration_ml: 0,
    serving_size: '1 knot + sauce',
    portion: '1 serving',
    confidence: 'high',
  },
  {
    id: 'log-soup',
    log_time: '2026-04-20T13:10:00.000Z',
    food_name: 'Lemon-Dill Mediterranean Chicken Soup',
    calories: 410,
    protein_g: 43.6,
    carbs_g: 32.7,
    fat_total_g: 14.8,
    fat_saturated_g: 3.3,
    fiber_g: 3.5,
    sugar_g: 5,
    sodium_mg: 533,
    hydration_ml: 0,
    serving_size: '18 oz bowl',
    portion: '18 oz',
    confidence: 'high',
  },
  {
    id: 'log-water-lunch',
    log_time: '2026-04-20T13:12:00.000Z',
    food_name: 'Water',
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    hydration_ml: 532,
    serving_size: '18 oz',
    portion: '18 oz',
    confidence: 'high',
  },
  {
    id: 'log-granola',
    log_time: '2026-04-19T14:00:00.000Z',
    food_name: 'MadeGood Birthday Cake Granola Bar',
    calories: 110,
    protein_g: 2,
    carbs_g: 17,
    fat_total_g: 3.5,
    fat_saturated_g: 1.5,
    fiber_g: 1,
    sugar_g: 6,
    sodium_mg: 35,
    hydration_ml: 0,
    serving_size: '24 g bar',
    portion: '1 bar',
    confidence: 'high',
  },
  {
    id: 'log-shrimp',
    log_time: '2026-04-19T18:30:00.000Z',
    food_name: 'Frozen shrimp saute',
    calories: 310,
    protein_g: 34,
    carbs_g: 5,
    fat_total_g: 17,
    fiber_g: 0,
    sugar_g: 1,
    sodium_mg: 910,
    hydration_ml: 0,
    serving_size: '1 plate',
    portion: '1 serving',
    confidence: 'medium',
    error_sources: ['unknown_preparation'],
  },
  {
    id: 'log-yogurt',
    log_time: '2026-04-18T08:05:00.000Z',
    food_name: 'Greek yogurt bowl',
    calories: 240,
    protein_g: 20,
    carbs_g: 19,
    fat_total_g: 8,
    fiber_g: 4,
    sugar_g: 12,
    sodium_mg: 120,
    hydration_ml: 0,
    serving_size: '1 bowl',
    portion: '1 serving',
    confidence: 'high',
  },
  {
    id: 'log-travel-wrap',
    log_time: '2026-04-17T12:15:00.000Z',
    food_name: 'Airport turkey wrap',
    calories: 520,
    protein_g: 28,
    carbs_g: 45,
    fat_total_g: 24,
    fiber_g: 4,
    sugar_g: 5,
    sodium_mg: 1120,
    hydration_ml: 0,
    serving_size: '1 wrap',
    portion: '1 serving',
    confidence: 'medium',
    error_sources: ['unknown_preparation'],
  },
  {
    id: 'log-travel-water',
    log_time: '2026-04-17T12:16:00.000Z',
    food_name: 'Water',
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    hydration_ml: 710,
    serving_size: '24 oz',
    portion: '24 oz',
    confidence: 'high',
  },
];

const recipes: DemoRecipe[] = [
  {
    id: 'recipe-soup',
    recipe_name: 'Lemon-Dill Mediterranean Chicken Soup',
    servings: 8,
    serving_size: '18 oz bowl',
    calories: 3280,
    description:
      'Bright and creamy chicken soup with lemon, herbs, spinach, and couscous. This is the exact recipe flow shown in the original app screenshots.',
    instructions:
      '1. Saute garlic, onion, fennel, and carrots.\n2. Simmer with broth and chicken thighs.\n3. Shred chicken and stir in couscous.\n4. Add peas and spinach.\n5. Finish with dill, basil, lemon zest, and vegan yogurt.\n6. Serve hot.',
    recipe_ingredients: [
      { ingredient_name: 'High oleic safflower oil', quantity: 1, unit: 'tbsp' },
      { ingredient_name: 'Garlic', quantity: 6, unit: 'cloves' },
      { ingredient_name: 'Yellow onion', quantity: 1, unit: 'whole' },
      { ingredient_name: 'Fennel bulb', quantity: 1, unit: 'small' },
      { ingredient_name: 'Carrots', quantity: 2, unit: 'large' },
      { ingredient_name: 'Low-sodium chicken broth', quantity: 6, unit: 'cups' },
      { ingredient_name: 'Chicken thighs', quantity: 3, unit: 'lb' },
      { ingredient_name: 'Fresh dill', quantity: 2, unit: 'tsp' },
      { ingredient_name: 'Fresh basil', quantity: 1, unit: 'tsp' },
      { ingredient_name: 'Pearl couscous', quantity: 1, unit: 'cup' },
      { ingredient_name: 'Frozen peas', quantity: 1, unit: 'cup' },
      { ingredient_name: 'Chopped spinach', quantity: 1, unit: 'cup' },
    ],
    per_serving_nutrition: {
      calories: 410,
      protein_g: 43.6,
      carbs_g: 32.7,
      fat_total_g: 14.8,
      fat_saturated_g: 3.3,
      fiber_g: 3.5,
      sugar_g: 5,
      sodium_mg: 533,
      hydration_ml: 0,
    },
    nutrition_data: {
      calories: 3280,
      protein_g: 348.8,
      carbs_g: 261.6,
      fat_total_g: 118.4,
      fat_saturated_g: 26.4,
      fiber_g: 28,
      sugar_g: 40,
      sodium_mg: 4264,
      hydration_ml: 0,
    },
  },
  {
    id: 'recipe-bowl',
    recipe_name: 'Chicken rice bowl',
    servings: 2,
    serving_size: '1 bowl',
    calories: 1240,
    description: 'Lean protein lunch bowl used for a clean high-protein comparison.',
    ingredients:
      'Chicken breast, jasmine rice, cucumber, greens, sesame dressing, pickled onions',
    per_serving_nutrition: {
      calories: 620,
      protein_g: 46,
      carbs_g: 58,
      fat_total_g: 18,
      fiber_g: 5,
      sugar_g: 7,
      sodium_mg: 780,
      hydration_ml: 0,
    },
  },
];

const defaultMessages = [
  {
    id: 'msg-welcome-bot',
    sender: 'bot' as const,
    text:
      "You're in the real NutriPal web flow now: chat on the left, tracker on the right, and the same pages the upstream app exposes in the sidebar. Use the quick options below the input to replay the key AI flows with dummy data.",
    message_type: 'analysis' as const,
  },
  {
    id: 'msg-summary-bot',
    sender: 'bot' as const,
    text:
      "I've updated your tracker with everything logged so far. Sodium is 1027 mg, water is 50 oz, and protein is 54.1 g toward your 132 g goal.",
    metadata: {
      progress_logs: logs.filter((log) => log.log_time.startsWith('2026-04-20')),
    },
    message_type: 'progress_logs' as const,
  },
];

const sessions: DemoChatSession[] = [
  {
    id: 'chat-main',
    title: 'Today walkthrough',
    updated_at: '2026-04-20T13:15:00.000Z',
    messages: defaultMessages,
  },
  {
    id: 'chat-audit',
    title: 'Sodium audit',
    updated_at: '2026-04-19T18:40:00.000Z',
    messages: [
      {
        id: 'msg-audit-user',
        sender: 'user',
        text: 'Do you think you have the right sodium number?',
      },
      {
        id: 'msg-audit-bot',
        sender: 'bot',
        text:
          "You're right to question the sodium value. Based on the product's audit flow, the biggest uncertainty drivers are processing, brine retention, and restaurant-sized portions, not the low-sodium items around it.",
        metadata: {
          progress_logs: [
            logs.find((log) => log.id === 'log-shrimp'),
            logs.find((log) => log.id === 'log-granola'),
          ].filter((log): log is DemoFoodLog => Boolean(log)),
        },
        message_type: 'audit',
      },
    ],
  },
];

const seedState: NutritionAssistantDemoState = {
  activePage: 'chat',
  activeChatId: 'chat-main',
  chatSessions: sessions,
  goals,
  logs,
  recipes,
  profile: {
    displayUnits: { volume: 'oz', weight: 'g', energy: 'kcal' },
    healthNotes: ['Colitis-aware fiber tracking', 'Keep sodium controlled when travel is not active'],
    dayType: 'normal',
  },
};

export function createNutritionAssistantSeed() {
  return JSON.parse(JSON.stringify(seedState)) as NutritionAssistantDemoState;
}
