import bizdevSeed from '@/data/dummy/bizdev-command-center.json';
import type { BizDevDemoState, CommandCenterState } from './types';

const seedState: CommandCenterState = {
  contacts: [
    {
      id: 'contact-harlan',
      name: 'Harlan Milner',
      role: 'Managing Partner',
      email: 'harlan@northharbor.co',
      additionalEmails: ['hmilner@signalmail.demo'],
      company: 'North Harbor Capital',
      type: 'host',
      area: 'founders',
      linkedinUrl: 'https://www.linkedin.com/in/harlan-milner-demo',
      isInThinkTank: false,
      currentProjects: ['Operator dinner host rotation', 'Founder salon sponsor mapping'],
      goalsAspirations: ['Build a stronger founder community in the Midwest'],
      strategicGoals: ['Keep a warm lane for future portfolio workshop referrals'],
      generalNotes: 'Trusted host profile with strong convening power and reliable follow-through.',
      createdAt: '2026-02-02T15:00:00.000Z',
    },
    {
      id: 'contact-elliot',
      name: 'Elliot Mercer',
      role: 'CEO',
      email: 'elliot@mobileflowlabs.com',
      additionalEmails: [],
      company: 'MobileFlow Labs',
      type: 'cto_club_member',
      area: 'engineering',
      linkedinUrl: 'https://www.linkedin.com/in/elliot-mercer-demo',
      isInThinkTank: true,
      currentProjects: ['Workflow observability rollout', 'AI pilot for support triage'],
      goalsAspirations: ['Meet peers shipping internal AI systems'],
      strategicGoals: ['Pressure-test C-Suite Think Tank programming against member needs'],
      generalNotes: 'Existing member and helpful feedback source for programming quality.',
      createdAt: '2026-01-17T10:30:00.000Z',
    },
    {
      id: 'contact-matthew',
      name: 'Mason Rivera',
      role: 'Founder',
      email: 'mason@signalforge.co',
      additionalEmails: ['m.rivera@signalforge.co'],
      company: 'SignalForge',
      type: 'established_connection',
      area: 'founders',
      linkedinUrl: 'https://www.linkedin.com/in/mason-rivera-demo',
      isInThinkTank: false,
      currentProjects: ['Founder salon attendee list', 'Operator warm-intro chain'],
      goalsAspirations: ['Expand founder peer circle for commercial partnerships'],
      strategicGoals: ['Use him as a bridge to later-stage founder operators'],
      generalNotes: 'Warm founder node with strong referral instincts.',
      createdAt: '2026-02-12T12:00:00.000Z',
    },
    {
      id: 'contact-miles',
      name: 'Miles Carter',
      role: 'VP of Operations',
      email: 'miles@growthgrid.io',
      additionalEmails: [],
      company: 'GrowthGrid',
      type: 'target_guest',
      area: 'product',
      linkedinUrl: 'https://www.linkedin.com/in/miles-carter-demo',
      isInThinkTank: false,
      currentProjects: ['KPI instrumentation cleanup'],
      goalsAspirations: ['Find operator peers solving reporting fragmentation'],
      strategicGoals: ['Convert dinner attendance into bizdev discovery'],
      generalNotes: 'Strong fit for product/operator breakfasts and reporting demo follow-up.',
      createdAt: '2026-03-03T09:20:00.000Z',
    },
    {
      id: 'contact-ethan',
      name: 'Evan Norwood',
      role: 'Partnership Lead',
      email: 'evan@olivehospitality.co',
      additionalEmails: [],
      company: 'Olive Hospitality',
      type: 'partner',
      area: 'events',
      linkedinUrl: 'https://www.linkedin.com/in/evan-norwood-demo',
      isInThinkTank: false,
      currentProjects: ['Venue shortlist for Q2 breakfast series'],
      goalsAspirations: ['Grow private event footprint with recurring operators series'],
      strategicGoals: ['Lock preferred pricing and tighter venue collaboration'],
      generalNotes: 'Operational partner with fast turnaround on event logistics.',
      createdAt: '2026-02-24T14:10:00.000Z',
    },
    {
      id: 'contact-neil',
      name: 'Nolan Gray',
      role: 'Advisor',
      email: 'nolan@haloadvisors.com',
      additionalEmails: ['n.gray@advisor-demo.com'],
      company: 'Halo Advisors',
      type: 'vip',
      area: 'founders',
      linkedinUrl: 'https://www.linkedin.com/in/nolan-gray-demo',
      isInThinkTank: false,
      currentProjects: ['Portfolio operator mapping', 'Strategic intros for SummitArc and Northlane'],
      goalsAspirations: ['Stay close to emerging operator ecosystems'],
      strategicGoals: ['Use Nolan as a high-trust introduction channel into key accounts'],
      generalNotes: 'Senior advisor profile who responds well to concise updates and specific asks.',
      createdAt: '2026-01-25T08:45:00.000Z',
    },
    {
      id: 'contact-mitch',
      name: 'Micah Voss',
      role: 'Founder',
      email: 'micah@ovyl.io',
      additionalEmails: [],
      company: 'Ovyl',
      type: 'potential_cto_club_member',
      area: 'engineering',
      linkedinUrl: 'https://www.linkedin.com/in/micah-voss-demo',
      isInThinkTank: false,
      currentProjects: ['Internal tooling stack refresh'],
      goalsAspirations: ['Meet engineering leaders with strong operating systems'],
      strategicGoals: ['Qualify as a think tank candidate and long-term connector'],
      generalNotes: 'Good candidate for the think tank pipeline after one deeper conversation.',
      createdAt: '2026-03-01T16:00:00.000Z',
    },
    {
      id: 'contact-serena',
      name: 'Serena Park',
      role: 'Head of Partnerships',
      email: 'serena@meridianevents.com',
      additionalEmails: ['spark@meridianevents.com'],
      company: 'Meridian Events',
      type: 'vip',
      area: 'events',
      linkedinUrl: 'https://www.linkedin.com/in/serena-park-demo',
      isInThinkTank: false,
      currentProjects: ['Leadership dinner series', 'Sponsor strategy refresh'],
      goalsAspirations: ['Expand premium event footprint with better operator targeting'],
      strategicGoals: ['Build a durable event distribution and co-hosting partnership'],
      generalNotes: 'Very valuable event strategy partner; strongest when discussions are concrete.',
      createdAt: '2026-02-08T11:20:00.000Z',
    },
    {
      id: 'contact-adrian',
      name: 'Adrian Wells',
      role: 'Chief of Staff',
      email: 'adrian@emberhealth.io',
      additionalEmails: [],
      company: 'Ember Health',
      type: 'vip',
      area: 'product',
      linkedinUrl: 'https://www.linkedin.com/in/adrian-wells-demo',
      isInThinkTank: false,
      currentProjects: ['Executive reporting overhaul', 'Leadership operating cadence'],
      goalsAspirations: ['Improve visibility for executive decisions without adding headcount'],
      strategicGoals: ['Turn strategic relationship into advisory or systems engagement'],
      generalNotes: 'Prefers sharp prep, concise notes, and concrete next steps over broad decks.',
      createdAt: '2026-02-18T13:15:00.000Z',
    },
    {
      id: 'contact-lena',
      name: 'Lena Brooks',
      role: 'Community Lead',
      email: 'lena@operatorroundtable.com',
      additionalEmails: [],
      company: 'Operator Roundtable',
      type: 'partner',
      area: 'community',
      linkedinUrl: 'https://www.linkedin.com/in/lena-brooks-demo',
      isInThinkTank: false,
      currentProjects: ['Member profile refresh', 'Quarterly community programming'],
      goalsAspirations: ['Clarify the right member mix for a peer group launch'],
      strategicGoals: ['Use this lane to refine the C-Suite Think Tank concept'],
      generalNotes: 'Strong collaborator for member profile and community design questions.',
      createdAt: '2026-03-06T09:00:00.000Z',
    },
    {
      id: 'contact-clara',
      name: 'Clara Weston',
      role: 'Program Manager',
      email: 'clara@northstarlogistics.com',
      additionalEmails: ['cweston@northstar.demo'],
      company: 'Northstar Logistics',
      type: 'guest',
      area: 'product',
      linkedinUrl: 'https://www.linkedin.com/in/clara-weston-demo',
      isInThinkTank: false,
      currentProjects: ['Ops reporting workshop scoping'],
      goalsAspirations: ['Reduce manual reporting burden for ops leaders'],
      strategicGoals: ['Move from workshop scoping into paid pilot'],
      generalNotes: 'Program owner with good visibility into practical pain points.',
      createdAt: '2026-03-09T07:30:00.000Z',
    },
    {
      id: 'contact-malik',
      name: 'Malik Torres',
      role: 'Research Analyst',
      email: 'malik@researchops.co',
      additionalEmails: [],
      company: 'Research Ops Studio',
      type: 'advisor',
      area: 'research',
      linkedinUrl: 'https://www.linkedin.com/in/malik-torres-demo',
      isInThinkTank: false,
      currentProjects: ['Sector transcripts summary library'],
      goalsAspirations: ['Systematize reusable market intelligence'],
      strategicGoals: ['Support repeatable research inputs for bizdev'],
      generalNotes: 'Helpful research operator for synthesis and source organization.',
      createdAt: '2026-02-27T17:15:00.000Z',
    },
    {
      id: 'contact-priya',
      name: 'Priya Raman',
      role: 'Chief Product Officer',
      email: 'priya@apertureflow.ai',
      additionalEmails: [],
      company: 'ApertureFlow',
      type: 'target_guest',
      area: 'product',
      linkedinUrl: 'https://www.linkedin.com/in/priya-raman-demo',
      isInThinkTank: false,
      currentProjects: ['AI workflow breakfast roundtable'],
      goalsAspirations: ['Learn how peers introduce AI into core team rituals'],
      strategicGoals: ['Use breakfast series to deepen product executive network'],
      generalNotes: 'High-signal product leader and strong candidate for future VIP cultivation.',
      createdAt: '2026-03-14T10:45:00.000Z',
    },
    {
      id: 'contact-omar',
      name: 'Omar Haddad',
      role: 'CTO',
      email: 'omar@helixcommerce.io',
      additionalEmails: [],
      company: 'Helix Commerce',
      type: 'potential_cto_club_member',
      area: 'engineering',
      linkedinUrl: 'https://www.linkedin.com/in/omar-haddad-demo',
      isInThinkTank: false,
      currentProjects: ['Engineering leadership offsite planning'],
      goalsAspirations: ['Find peers focused on modern engineering management'],
      strategicGoals: ['Bring into the think tank pipeline after founder referral'],
      generalNotes: 'Strong senior operator fit for the C-suite community lane.',
      createdAt: '2026-03-16T11:00:00.000Z',
    },
  ],
  events: [
    {
      id: 'event-operator-dinner',
      name: 'Operator Dinner Series',
      eventType: 'product',
      eventDate: '2026-05-02T18:30:00.000Z',
      status: 'Invitations Sent',
      venue: 'The Atlas Room',
      description: 'Warm-intro dinner for product and operations leaders exploring AI-enabled operating systems.',
      guestCount: 26,
      maxAttendees: 30,
      createdAt: '2026-03-19T10:00:00.000Z',
    },
    {
      id: 'event-ai-breakfast',
      name: 'AI Systems Breakfast',
      eventType: 'engineering',
      eventDate: '2026-05-18T08:30:00.000Z',
      status: 'Planning',
      venue: 'North Hall Club',
      description: 'Invite-only breakfast for engineering and product operators evaluating internal AI workflows.',
      guestCount: 14,
      maxAttendees: 24,
      createdAt: '2026-03-23T08:30:00.000Z',
    },
    {
      id: 'event-founder-salon',
      name: 'Founder Salon',
      eventType: 'startup',
      eventDate: '2026-04-11T18:00:00.000Z',
      status: 'Completed',
      venue: 'Private Residence',
      description: 'Small-group salon for founders and strategic partners with heavy emphasis on relationship quality.',
      guestCount: 19,
      maxAttendees: 22,
      createdAt: '2026-03-02T12:00:00.000Z',
    },
    {
      id: 'event-portfolio-forum',
      name: 'Portfolio Forum',
      eventType: 'startup',
      eventDate: '2026-04-24T12:00:00.000Z',
      status: 'In Progress',
      venue: 'Harbor House',
      description: 'Working lunch for portfolio operators and advisors focused on operational reporting and follow-up systems.',
      guestCount: 31,
      maxAttendees: 36,
      createdAt: '2026-03-28T15:10:00.000Z',
    },
    {
      id: 'event-think-tank-preview',
      name: 'C-Suite Think Tank Preview',
      eventType: 'cto_club',
      eventDate: '2026-05-27T17:30:00.000Z',
      status: 'Planning',
      venue: 'Juniper Loft',
      description: 'Preview session to validate member fit, cadence, and programming for the peer group.',
      guestCount: 9,
      maxAttendees: 14,
      createdAt: '2026-04-01T09:00:00.000Z',
    },
  ],
  pipeline: [
    {
      id: 'pipeline-serena',
      contactId: 'contact-serena',
      stage: 'Maintaining the Relationship',
      nextAction: 'Finalize co-host brief and sponsor target list for the operator dinner.',
      nextActionDate: '2026-04-28',
      lastActionDate: '2026-04-16',
      notes: 'High-leverage event partner; best conversations stay grounded in concrete execution.',
    },
    {
      id: 'pipeline-adrian',
      contactId: 'contact-adrian',
      stage: 'Forming the Relationship',
      nextAction: 'Share sanitized reporting demo and ask where exec visibility still breaks down.',
      nextActionDate: '2026-04-25',
      lastActionDate: '2026-04-14',
      notes: 'Strong possible advisory lane if trust continues to build.',
    },
    {
      id: 'pipeline-clara',
      contactId: 'contact-clara',
      stage: 'Forming the Relationship',
      nextAction: 'Schedule workshop scoping call with operations and finance leads.',
      nextActionDate: '2026-04-23',
      lastActionDate: '2026-04-11',
      notes: 'Very close to a concrete workshop opportunity around reporting operations.',
    },
    {
      id: 'pipeline-neil',
      contactId: 'contact-neil',
      stage: 'Maintaining the Relationship',
      nextAction: 'Ask for two operator introductions that fit SummitArc and Northlane.',
      nextActionDate: '2026-04-26',
      lastActionDate: '2026-04-12',
      notes: 'Responds well to short updates and narrow asks.',
    },
    {
      id: 'pipeline-lena',
      contactId: 'contact-lena',
      stage: 'Initial Outreach',
      nextAction: 'Send the latest member profile draft and ask for a 20-minute feedback block.',
      nextActionDate: '2026-04-24',
      lastActionDate: '2026-04-10',
      notes: 'Useful collaborator for refining the community angle of the think tank.',
    },
    {
      id: 'pipeline-priya',
      contactId: 'contact-priya',
      stage: 'Initial Outreach',
      nextAction: 'Follow up on breakfast invite with a concise note about peer mix and format.',
      nextActionDate: '2026-04-29',
      lastActionDate: '2026-04-18',
      notes: 'Good target guest for the AI systems breakfast.',
    },
  ],
  vipProfiles: [
    {
      id: 'vip-profile-adrian',
      contactId: 'contact-adrian',
      priority: 'High',
      relationshipSummary: 'Trusted strategic relationship with strong interest in operating systems, follow-up discipline, and executive visibility.',
      objective: 'Support Ember Health\'s operating cadence while positioning future advisory or systems work.',
      nextStep: 'Prep a tailored briefing before the next operating review call.',
      tags: ['healthcare', 'executive-ops', 'reporting'],
      initiatives: [
        {
          id: 'vip-initiative-adrian-1',
          title: 'Package a sanitized reporting walkthrough',
          type: 'give',
          status: 'active',
          detail: 'Share a concrete example of how leadership reporting can tighten weekly decision-making.',
        },
        {
          id: 'vip-initiative-adrian-2',
          title: 'Clarify decision bottlenecks before the June planning cycle',
          type: 'ask',
          status: 'planned',
          detail: 'Request a candid overview of where the current cadence breaks down across leadership.',
        },
      ],
      activities: [
        {
          id: 'vip-activity-adrian-1',
          date: '2026-04-14',
          type: 'meeting',
          summary: 'Debriefed executive reporting pain points and current prep burden.',
        },
        {
          id: 'vip-activity-adrian-2',
          date: '2026-04-17',
          type: 'email',
          summary: 'Sent a short follow-up with potential structure for an operating brief.',
        },
      ],
    },
    {
      id: 'vip-profile-neil',
      contactId: 'contact-neil',
      priority: 'High',
      relationshipSummary: 'Longer-standing advisor relationship with strong leverage in warm intros and signal on operator talent.',
      objective: 'Stay useful and specific so asks feel easy and high-trust.',
      nextStep: 'Send a short status note and ask for two intros tied to live opportunities.',
      tags: ['advisor', 'introductions', 'portfolio'],
      initiatives: [
        {
          id: 'vip-initiative-neil-1',
          title: 'Send concise opportunity memo',
          type: 'give',
          status: 'active',
          detail: 'Keep Nolan equipped with a clean picture of where introductions would help most.',
        },
        {
          id: 'vip-initiative-neil-2',
          title: 'Request intros into two operator accounts',
          type: 'ask',
          status: 'active',
          detail: 'Make a specific introduction ask tied to current BizDev opportunities.',
        },
      ],
      activities: [
        {
          id: 'vip-activity-neil-1',
          date: '2026-04-12',
          type: 'note',
          summary: 'Updated advisor brief with changes across the SummitArc and Northlane lanes.',
        },
        {
          id: 'vip-activity-neil-2',
          date: '2026-04-18',
          type: 'email',
          summary: 'Shared a concise intro request framework.',
        },
      ],
    },
    {
      id: 'vip-profile-serena',
      contactId: 'contact-serena',
      priority: 'Medium',
      relationshipSummary: 'High-value event partner relationship with shared upside around better guest targeting and follow-up loops.',
      objective: 'Deepen the partnership around curated leadership events and sponsor alignment.',
      nextStep: 'Confirm the guest split and sponsor lane for the next dinner series.',
      tags: ['events', 'partnerships', 'community'],
      initiatives: [
        {
          id: 'vip-initiative-serena-1',
          title: 'Share post-event feedback digest',
          type: 'give',
          status: 'active',
          detail: 'Package attendee themes so future events feel increasingly well targeted.',
        },
        {
          id: 'vip-initiative-serena-2',
          title: 'Ask for a pilot co-host cadence',
          type: 'ask',
          status: 'planned',
          detail: 'Test a repeatable event rhythm with shared sponsor and guest strategy.',
        },
      ],
      activities: [
        {
          id: 'vip-activity-serena-1',
          date: '2026-04-16',
          type: 'meeting',
          summary: 'Reviewed event calendar and where higher-intent guests have come from.',
        },
      ],
    },
  ],
  ctoLeads: [
    {
      id: 'cto-1',
      name: 'Micah Voss',
      company: 'Ovyl',
      status: 'Potential',
      introSource: 'Founder referral',
      nextAction: 'Review fit against the C-Suite Think Tank member profile.',
    },
    {
      id: 'cto-2',
      name: 'Omar Haddad',
      company: 'Helix Commerce',
      status: 'In Pipeline',
      introSource: 'Community overlap',
      nextAction: 'Schedule a discovery conversation and share the preview dinner note.',
    },
    {
      id: 'cto-3',
      name: 'Elliot Mercer',
      company: 'MobileFlow Labs',
      status: 'Current Member',
      introSource: 'Existing network',
      nextAction: 'Capture feedback on current programming value.',
    },
  ],
  bizdev: bizdevSeed as BizDevDemoState,
};

export function createCommandCenterSeed(): CommandCenterState {
  return JSON.parse(JSON.stringify(seedState)) as CommandCenterState;
}
