import bizdevSeed from '@/data/dummy/bizdev-command-center.json';
import type { BizDevDemoState, CommandCenterState } from './types';

const seedState: CommandCenterState = {
  contacts: [
    {
      id: 'contact-harbor',
      name: 'Harlan Milner',
      role: 'Managing partner',
      email: 'harlan@northharbor.co',
      company: 'North Harbor Capital',
      type: 'guest',
      area: null,
      linkedinUrl: 'https://www.linkedin.com/in/harlan-milner-demo',
    },
    {
      id: 'contact-andrew',
      name: 'Andrew L. Grinde',
      role: 'CEO',
      email: 'andrew@mobileflowlabs.com',
      company: 'MobileFlow Labs',
      type: 'guest',
      area: null,
      linkedinUrl: 'https://www.linkedin.com/in/andrew-grinde-demo',
    },
    {
      id: 'contact-matthew',
      name: 'Matthew Rotondo',
      role: 'Founder',
      email: 'matthew@signal23.com',
      company: 'Signal23',
      type: 'guest',
      area: null,
      linkedinUrl: 'https://www.linkedin.com/in/matthew-rotondo-demo',
    },
    {
      id: 'contact-nathan',
      name: 'Nathan Gonzalez',
      role: 'Operator',
      email: 'nathan@growthgrid.io',
      company: 'GrowthGrid',
      type: 'guest',
      area: null,
    },
    {
      id: 'contact-ethan',
      name: 'Ethan Orley',
      role: 'Partnership lead',
      email: 'ethan@olivehospitality.co',
      company: 'Olive Hospitality',
      type: 'guest',
      area: null,
    },
    {
      id: 'contact-neil',
      name: 'Neil Granberry',
      role: 'Advisor',
      email: 'neil@haloadvisors.com',
      company: 'Halo Advisors',
      type: 'advisor',
      area: 'partnerships',
      linkedinUrl: 'https://www.linkedin.com/in/neil-granberry-demo',
    },
    {
      id: 'contact-mitch',
      name: 'Mitch Meiss',
      role: 'Founder',
      email: 'mitch@ovyl.io',
      company: 'Ovyl',
      type: 'founder',
      area: 'community',
    },
    {
      id: 'contact-serena',
      name: 'Serena Park',
      role: 'Head of partnerships',
      email: 'serena@meridianevents.com',
      company: 'Meridian Events',
      type: 'partner',
      area: 'events',
    },
    {
      id: 'contact-daniel',
      name: 'Daniel Shah',
      role: 'Chief of staff',
      email: 'daniel@emberhealth.io',
      company: 'Ember Health',
      type: 'vip',
      area: 'research',
    },
    {
      id: 'contact-june',
      name: 'June Patel',
      role: 'Community lead',
      email: 'june@operatorroundtable.com',
      company: 'Operator Roundtable',
      type: 'partner',
      area: 'community',
    },
    {
      id: 'contact-clara',
      name: 'Clara Weston',
      role: 'Program manager',
      email: 'clara@northstarlogistics.com',
      company: 'Northstar Logistics',
      type: 'guest',
      area: 'events',
    },
    {
      id: 'contact-malik',
      name: 'Malik Torres',
      role: 'Research analyst',
      email: 'malik@researchops.co',
      company: 'Research Ops Studio',
      type: 'advisor',
      area: 'research',
    }
  ],
  events: [
    {
      id: 'event-operator-dinner',
      name: 'Operator Dinner Series',
      eventDate: '2026-05-02T18:30:00.000Z',
      status: 'Invitations Sent',
      venue: 'The Atlas Room',
      focus: 'Warm-intro dinner for product and operations leaders',
      guestCount: 26,
    },
    {
      id: 'event-ai-breakfast',
      name: 'AI Systems Breakfast',
      eventDate: '2026-05-18T08:30:00.000Z',
      status: 'Draft',
      venue: 'North Hall Club',
      focus: 'Invite-only breakfast for operators exploring AI workflows',
      guestCount: 14,
    },
    {
      id: 'event-founder-salon',
      name: 'Founder Salon',
      eventDate: '2026-04-11T18:00:00.000Z',
      status: 'Completed',
      venue: 'Private Residence',
      focus: 'Small-group salon for founders and strategic partners',
      guestCount: 19,
    },
    {
      id: 'event-portfolio-forum',
      name: 'Portfolio Forum',
      eventDate: '2026-04-24T12:00:00.000Z',
      status: 'In Progress',
      venue: 'Harbor House',
      focus: 'Working session for portfolio operators and advisors',
      guestCount: 31,
    }
  ],
  pipeline: [
    {
      id: 'pipeline-serena',
      contactId: 'contact-serena',
      stage: 'Strategic Partner',
      nextAction: 'Finalize host brief and sponsor targets',
      nextActionDate: '2026-04-28',
      notes: 'High leverage for event strategy and guest curation.',
    },
    {
      id: 'pipeline-daniel',
      contactId: 'contact-daniel',
      stage: 'Building Relationship',
      nextAction: 'Share sanitized reporting demo follow-up',
      nextActionDate: '2026-04-25',
      notes: 'Interested in follow-up systems and exec visibility.',
    },
    {
      id: 'pipeline-clara',
      contactId: 'contact-clara',
      stage: 'Connected',
      nextAction: 'Schedule workshop scoping call',
      nextActionDate: '2026-04-23',
      notes: 'Strong fit for operations reporting sprint.',
    },
    {
      id: 'pipeline-neil',
      contactId: 'contact-neil',
      stage: 'Strategic Partner',
      nextAction: 'Ask for two operator introductions',
      nextActionDate: '2026-04-26',
      notes: 'Reliable advisor channel.',
    },
    {
      id: 'pipeline-june',
      contactId: 'contact-june',
      stage: 'Initial Outreach',
      nextAction: 'Send community launch one-pager',
      nextActionDate: '2026-04-24',
      notes: 'Good fit for roundtable collaboration.',
    },
    {
      id: 'pipeline-mitch',
      contactId: 'contact-mitch',
      stage: 'New Contact',
      nextAction: 'Warm intro note via shared founder',
      nextActionDate: '2026-04-27',
      notes: 'Potential founder ecosystem bridge.',
    }
  ],
  vipProfiles: [
    {
      id: 'vip-1',
      name: 'Daniel Shah',
      company: 'Ember Health',
      priority: 'High',
      objective: 'Support expansion conversation and capture reporting pain points.',
      nextStep: 'Prep tailored briefing before Tuesday call.',
    },
    {
      id: 'vip-2',
      name: 'Neil Granberry',
      company: 'Halo Advisors',
      priority: 'High',
      objective: 'Strengthen intro path into three target operator accounts.',
      nextStep: 'Send quick update and ask for two warm intros.',
    },
    {
      id: 'vip-3',
      name: 'Serena Park',
      company: 'Meridian Events',
      priority: 'Medium',
      objective: 'Deepen partnership around curated dinner series.',
      nextStep: 'Confirm guest list split and sponsor lane.',
    }
  ],
  ctoLeads: [
    {
      id: 'cto-1',
      name: 'Mitch Meiss',
      company: 'Ovyl',
      status: 'Potential',
      introSource: 'Founder referral',
      nextAction: 'Review fit against member profile.',
    },
    {
      id: 'cto-2',
      name: 'June Patel',
      company: 'Operator Roundtable',
      status: 'In Pipeline',
      introSource: 'Community overlap',
      nextAction: 'Schedule discovery conversation.',
    },
    {
      id: 'cto-3',
      name: 'Andrew L. Grinde',
      company: 'MobileFlow Labs',
      status: 'Current Member',
      introSource: 'Existing network',
      nextAction: 'Capture feedback on member value.',
    }
  ],
  bizdev: bizdevSeed as BizDevDemoState,
};

export function createCommandCenterSeed(): CommandCenterState {
  return JSON.parse(JSON.stringify(seedState)) as CommandCenterState;
}
